<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Account</name>
   <tag></tag>
   <elementGuidId>5487e6cd-9093-4dd8-aef5-f1d4322baa92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navbarAccount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='navbarAccount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Show/hide account menu&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8217bd45-3531-4c53-ace3-5972f9537f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show/hide account menu</value>
      <webElementGuid>b5e9dad6-c126-484b-8916-544f62f45a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navbarAccount</value>
      <webElementGuid>7b7ea08e-5600-4c6c-be72-68809ccd2943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-menu-trigger buttons mat-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>1ecabd0d-d306-4430-9ae2-f09dbaae9ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>34558853-3e5f-43e5-a390-9baa252cc94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> account_circle  Account </value>
      <webElementGuid>3b189714-0315-4143-9e74-772cf54597c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarAccount&quot;)</value>
      <webElementGuid>4e41b7a6-1940-4697-99a2-e45ce03d3365</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='navbarAccount']</value>
      <webElementGuid>85013a3e-0449-4066-9edd-269e2d285205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OWASP Juice Shop'])[4]/following::button[1]</value>
      <webElementGuid>f098a9bb-5b66-45c3-ad3e-49f9aecf296f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v17.1.1'])[1]/following::button[3]</value>
      <webElementGuid>3a5faba6-742f-4bf4-8357-682f354b5849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>7ff7727b-a39e-47da-b3be-222d603e3305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'navbarAccount' and (text() = ' account_circle  Account ' or . = ' account_circle  Account ')]</value>
      <webElementGuid>c00c88eb-f9c8-4b76-9101-b231fd684967</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
