<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MobileNumber</name>
   <tag></tag>
   <elementGuidId>a43a90c6-e749-4ca2-a011-4988ca525ecc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-input-11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Please provide a mobile number.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bc09504-20a6-41a3-bd1a-8d371dfadd28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5018f84f-eec4-49b4-a184-31afdbb626c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c21-25 ng-pristine ng-invalid cdk-text-field-autofill-monitored ng-touched</value>
      <webElementGuid>bad3f276-eaf5-4209-a08b-82558c01d875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please provide a mobile number.</value>
      <webElementGuid>c41a190c-9a69-4371-8466-a251fc4797d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-11</value>
      <webElementGuid>4377ceb2-b95c-4ad6-b705-c2ddcc7f4d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Please provide a mobile number.</value>
      <webElementGuid>468cb70d-0812-4a71-8a81-2da2aca1d741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2387ada3-839b-4671-926a-8d934ebbb6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mat-error-20</value>
      <webElementGuid>2cf5eeec-49f8-47fc-a950-8bc750c74c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-11&quot;)</value>
      <webElementGuid>9e46d77f-9df6-4bc3-8834-22ea9d45d2b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-11']</value>
      <webElementGuid>b377a899-657d-4fd2-a8f5-ab8b0275acfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-form']/mat-form-field[3]/div/div/div[3]/input</value>
      <webElementGuid>096cd3e1-b602-480c-83b3-b0f9cbc80c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[3]/div/div/div[3]/input</value>
      <webElementGuid>29216f24-34f2-49ac-a83a-00ca3da53028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Please provide a mobile number.' and @id = 'mat-input-11']</value>
      <webElementGuid>9b1fe480-a4d9-4ad1-b451-c12687ad1ef9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
