<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Delivery3Days</name>
   <tag></tag>
   <elementGuidId>16300f15-3414-4929-98c9-6eea8760893b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-radio-44 > label.mat-radio-label > span.mat-radio-container > span.mat-radio-outer-circle</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mat-radio-44&quot;)/label[@class=&quot;mat-radio-label&quot;]/span[@class=&quot;mat-radio-container&quot;]/span[@class=&quot;mat-radio-inner-circle&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-radio-button[@id='mat-radio-44']/label/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mat-radio-44 > .mat-radio-label > .mat-radio-container > .mat-radio-outer-circle</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>603ccdc3-44ef-4398-865e-dac92b667799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-radio-inner-circle</value>
      <webElementGuid>2d80bd21-8dbe-4344-9ec7-c1ba2207e680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-radio-44&quot;)/label[@class=&quot;mat-radio-label&quot;]/span[@class=&quot;mat-radio-container&quot;]/span[@class=&quot;mat-radio-inner-circle&quot;]</value>
      <webElementGuid>7dce8033-3614-45fd-ac87-c3704faed902</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-radio-button[@id='mat-radio-44']/label/span/span</value>
      <webElementGuid>f174d919-dfe9-4daf-9f5a-d4bbae1b7dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-row[2]/mat-cell/mat-radio-button/label/span/span</value>
      <webElementGuid>8c71dd35-f33f-4319-ae38-df7caeb2df41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
