<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Delivery1Day</name>
   <tag></tag>
   <elementGuidId>a751f36a-39ea-49bc-b318-564755f582d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mat-radio-outer-circle</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mat-radio-43&quot;)/label[@class=&quot;mat-radio-label&quot;]/span[@class=&quot;mat-radio-container&quot;]/span[@class=&quot;mat-radio-inner-circle&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-radio-button[@id='mat-radio-43']/label/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.mat-radio-outer-circle >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>875a361c-e58a-4422-b8d2-a0d2f14ff2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-radio-inner-circle</value>
      <webElementGuid>09ed391c-e7b0-48ae-a6ff-887e34fb9da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-radio-43&quot;)/label[@class=&quot;mat-radio-label&quot;]/span[@class=&quot;mat-radio-container&quot;]/span[@class=&quot;mat-radio-inner-circle&quot;]</value>
      <webElementGuid>441d3a56-4fdb-429d-9f37-16f60dd0bc79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-radio-button[@id='mat-radio-43']/label/span/span</value>
      <webElementGuid>00d904dd-3ee1-46be-931e-f4d10cab20bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span/span</value>
      <webElementGuid>571eb83b-760f-4ad6-b190-8a060007cebc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
